Insert into RESERVATION
(RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, CREATE_DATE, GUEST_ID, HOTEL_ID, UPDATE_DATE, STATE, TOTAL_AMOUNT) 
values(1, '2021-02-01', '2021-02-02', '2021-01-29', 1, 1, '2021-01-29', 'BOOKING', 1000.0);

Insert into RESERVATION_LINE_DETAILS
(RESERVATION_LINE_ID, AMOUNT_PER_ROOM, CHECK_IN_DATE, CHECK_OUT_DATE, ROOM_ID, RESERVATION_RESERVATION_ID) 
values (1, 1000.0, '2021-02-01', '2021-02-02', 1, 1);

Insert into GUEST_DETAILS
(GUEST_ID, CITY, COUNTRY, EMAIL, FIRST_NAME, GENDER, HOUSE_NUMBER, LAST_NAME, MIDDEL_NAME, PHONE_NUMBER, STATE, STREET, ZIPCODE, RESERVATION_LINE_DETAILS_RESERVATION_LINE_ID)
values(1, 'Indore', 'India', 'arvind@abc.com', 'arvind', 'M', '1', 'jain', 'kumar', 12121212, 'Madhya Pradesh', 'Nagar Road', 452006, 1);

Insert into Payment_details
(PAYMENT_ID, CARD_HOLDER_NAME, CC_TYPE, CREDIT_CARD_NUMBER, CC_CVV_NUMBER, EXPIRY_DATE, GUEST_ID, RESERVATION_ID)
values(1, 'arvind', 'VISA', 12121212, 123,  '2021-12-31', 1, 1);

Insert into INVENTORY_DETAILS
(RESERVATION_INVENTORY_ID, AMOUNT_PER_NIGHT, INVENTORY_ID, ROOM_ID, STAY_DATE, RESERVATION_LINE_DETAILS_RESERVATION_LINE_ID) values (1, 500.0, 1, 1, '2021-02-01', 1);

Insert into INVENTORY_DETAILS
(RESERVATION_INVENTORY_ID, AMOUNT_PER_NIGHT, INVENTORY_ID, ROOM_ID, STAY_DATE, RESERVATION_LINE_DETAILS_RESERVATION_LINE_ID) values (2, 500.0, 2, 1, '2021-02-02',1); 